import styles from "./about.module.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <nav>About Navbar</nav>
      <main className="min-h-screen grid place-content-center bg-slate-400">
        {children}
      </main>
    </>
  );
}
